export const allQuestions = [
    {
      "id": "1",
      "description": "El padrastro de Jesús",
      "cite": "Mateo 1:18-19",
      "book": "mateo",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "2",
      "description": "El lugar donde nació Jesús",
      "cite": "Lucas 2:1-7",
      "book": "lucas",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "3",
      "description": "El nombre del ángel que anunció el nacimiento de Jesús a María",
      "cite": "Lucas 1:26-38",
      "book": "lucas",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "4",
      "description": "El símbolo del Espíritu Santo en la concepción de Jesús",
      "cite": "Mateo 1:18",
      "book": "mateo",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "5",
      "description": "El nombre del profeta que predijo el nacimiento de Jesús",
      "cite": "Isaías 7:14",
      "book": "isaías",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "6",
      "description": "El número de pastores que visitaron a Jesús al nacer",
      "cite": "Lucas 2:8-20",
      "book": "lucas",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "7",
      "description": "El nombre del rey mago que trajo oro",
      "cite": "Mateo 2:1-12",
      "book": "mateo",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "8",
      "description": "El nombre del rey mago que trajo incienso",
      "cite": "Mateo 2:1-12",
      "book": "mateo",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "9",
      "description": "El nombre del rey mago que trajo mirra",
      "cite": "Mateo 2:1-12",
      "book": "mateo",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "10",
      "description": "El lugar donde los reyes magos encontraron a Jesús",
      "cite": "Mateo 2:1-12",
      "book": "mateo",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "11",
      "description": "El nombre del profeta que predijo la muerte y resurrección de Jesús",
      "cite": "Isaías 53:1-12",
      "book": "isaías",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "12",
      "description": "El nombre del discípulo que traicionó a Jesús",
      "cite": "Mateo 26:14-16",
      "book": "mateo",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "13",
      "description": "El lugar donde Jesús fue crucificado",
      "cite": "Juan 19:17-30",
      "book": "juan",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "14",
      "description": "El nombre del discípulo que negó a Jesús tres veces",
      "cite": "Mateo 26:33-35",
      "book": "mateo",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "15",
      "description": "El nombre del discípulo que vio a Jesús resucitado primero",
      "cite": "Juan 20:1-18",
      "book": "juan",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "16",
      "description": "El nombre del apóstol que escribió más libros de la Biblia",
      "cite": "N/A",
      "book": "N/A",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "17",
      "description": "El nombre del apóstol que fue conocido como el 'apóstol de los gentiles'",
      "cite": "Romanos 11:13",
      "book": "romanos",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
     {
      "id": "18",
      "description": "El nombre del apóstol que escribió el libro de Apocalipsis",
      "cite": "Apocalipsis 1:1",
      "book": "apocalipsis",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "19",
      "description": "El nombre del apóstol que escribió las cartas a los Corintios",
      "cite": "1 Corintios 1:1",
      "book": "1 corintios",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "20",
      "description": "El nombre del apóstol que escribió las cartas a los Romanos",
      "cite": "Romanos 1:1",
      "book": "romanos",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "21",
      "description": "El nombre del apóstol que escribió las cartas a los Efesios",
      "cite": "Efesios 1:1",
      "book": "efesios",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "22",
      "description": "El nombre del apóstol que escribió las cartas a los Filipenses",
      "cite": "Filipenses 1:1",
      "book": "filipenses",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "23",
      "description": "El nombre del apóstol que escribió las cartas a los Colosenses",
      "cite": "Colosenses 1:1",
      "book": "colosenses",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "24",
      "description": "El nombre del apóstol que escribió las cartas a los Tesalonicenses",
      "cite": "1 Tesalonicenses 1:1",
      "book": "1 tesalonicenses",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "25",
      "description": "El nombre del apóstol que escribió las cartas a Timoteo",
      "cite": "1 Timoteo 1:1",
      "book": "1 timoteo",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "26",
      "description": "El nombre del apóstol que escribió las cartas a Tito",
      "cite": "Tito 1:1",
      "book": "tito",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "27",
      "description": "El nombre del apóstol que escribió la carta a Filemón",
      "cite": "Filemón 1:1",
      "book": "filemón",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "28",
      "description": "El nombre del evangelista que escribió el Evangelio de Marcos",
      "cite": "Marcos 1:1",
      "book": "marcos",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "29",
      "description": "El nombre del evangelista que escribió el Evangelio de Lucas",
      "cite": "Lucas 1:1",
      "book": "lucas",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "30",
      "description": "El nombre del evangelista que escribió el Evangelio de Juan",
      "cite": "Juan 1:1",
      "book": "juan",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "31",
      "description": "El nombre del autor de los Hechos de los Apóstoles",
      "cite": "Hechos 1:1",
      "book": "hechos",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "32",
      "description": "El nombre del autor de las cartas de Pedro",
      "cite": "1 Pedro 1:1",
      "book": "1 pedro",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "33",
      "description": "El nombre del autor de las cartas de Santiago",
      "cite": "Santiago 1:1",
      "book": "santiago",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
     {
      "id": "34",
      "description": "El nombre del autor de las cartas de Judas",
      "cite": "Judas 1:1",
      "book": "judas",
      "book_type": "new",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "35",
      "description": "El nombre del profeta que predijo la venida del Mesías",
      "cite": "Isaías 9:6",
      "book": "isaías",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "36",
      "description": "El nombre del profeta que predijo la resurrección de Jesús",
      "cite": "Salmo 16:10",
      "book": "salmos",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "37",
      "description": "El nombre del profeta que predijo la ascensión de Jesús al cielo",
      "cite": "Salmo 47:5",
      "book": "salmos",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "38",
      "description": "El nombre del profeta que predijo la segunda venida de Jesús",
      "cite": "Zecharías 14:4-9",
      "book": "zecharías",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "39",
      "description": "El nombre del profeta que predijo la destrucción de Jerusalén",
      "cite": "Jeremías 25:1-14",
      "book": "jeremías",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "40",
      "description": "El nombre del profeta que predijo la restauración de Israel",
      "cite": "Ezequiel 37:1-14",
      "book": "ezequiel",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "41",
      "description": "El nombre del profeta que predijo la venida del Espíritu Santo",
      "cite": "Joel 2:28-32",
      "book": "joel",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "42",
      "description": "El nombre del profeta que predijo el juicio final",
      "cite": "Malaquías 3:1-6",
      "book": "malaquías",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "43",
      "description": "El nombre del rey de Israel que fue conocido como 'el hombre según el corazón de Dios'",
      "cite": "1 Samuel 13:14",
      "book": "1 samuel",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "44",
      "description": "El nombre del rey de Israel que fue conocido como 'el rey sabio'",
      "cite": "1 Reyes 3:12",
      "book": "1 reyes",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "45",
      "description": "El nombre del rey de Israel que fue conocido como 'el rey pecador'",
      "cite": "1 Reyes 11:1-8",
      "book": "1 reyes",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "46",
      "description": "El nombre del rey de Judá que fue conocido como 'el rey bueno'",
      "cite": "2 Reyes 22:1-2",
      "book": "2 reyes",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "47",
      "description": "El nombre del rey de Judá que fue conocido como 'el rey malo'",
      "cite": "2 Reyes 21:1-9",
      "book": "2 reyes",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "48",
      "description": "El nombre del profeta que fue conocido como 'el profeta de la justicia'",
      "cite": "Jeremías 23:5",
      "book": "jeremías",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "49",
      "description": "El nombre del profeta que fue conocido como 'el profeta de la desolación'",
      "cite": "Ezequiel 3:10-11",
      "book": "ezequiel",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
    {
      "id": "50",
      "description": "El nombre del profeta que fue conocido como 'el profeta de la restauración'",
      "cite": "Daniel 1:1",
      "book": "daniel",
      "book_type": "old",
      "comodin_cite_used": false,
      "comodin_call_used": false,
      "comodin_5050_used": false,
      "is_proceed": false,
    },
  ];